"""Assemble deploy/docker-compose.yml: one self-contained file (configs inlined) for Hostinger Docker Manager."""
import base64
import os

HERE = os.path.dirname(os.path.abspath(__file__))


def read(path):
    return open(os.path.join(HERE, path), encoding="utf-8").read()


def block(text, indent=6):
    # Compose interpolates $ in config content; escape every literal $.
    pad = " " * indent
    return "\n".join(pad + line if line else "" for line in text.replace("$", "$$").splitlines())


photo = base64.b64encode(open(os.path.join(HERE, "site/charles.jpg"), "rb").read()).decode()
index = read("site/index.html").replace('src="charles.jpg"', f'src="data:image/jpeg;base64,{photo}"')
caddyfile = read("Caddyfile").replace("#ASSESS_BLOCK#", read("assess.caddy") if os.path.exists(os.path.join(HERE, "assess.caddy")) else "")

compose = f"""# GENERATED by consulting/build.py. Edit the sources, then rebuild.
name: crm-consulting

services:
  edge:
    image: caddy:2.11.7-alpine
    restart: unless-stopped
    ports:
      # Overridable so a rehearsal can run on hidden local ports beside the live site.
      - "${{HTTP_BIND:-80}}:80"
      - "${{HTTPS_BIND:-443}}:443"
      - "${{HTTPS_BIND:-443}}:443/udp"
    environment:
      SITE_DOMAIN: ${{SITE_DOMAIN:-executivecapacitymap.com}}
      ACME_EMAIL: ${{ACME_EMAIL:-charles@executivecapacitymap.com}}
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile
      - source: site_index
        target: /srv/site/index.html
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ${{ASSESS_WWW:-/opt/ecm/www}}:/srv/assess:ro
    depends_on:
      - intake

  intake:
    image: python:3.13-alpine
    restart: unless-stopped
    command: ["python", "-u", "/app/intake.py"]
    environment:
      SMTP_HOST: ${{SMTP_HOST:-smtp.hostinger.com}}
      SMTP_PORT: ${{SMTP_PORT:-465}}
      SMTP_USER: ${{SMTP_USER:-charles@executivecapacitymap.com}}
      SMTP_PASSWORD: ${{SMTP_PASSWORD:-}}
      INTAKE_TO: ${{INTAKE_TO:-charles@executivecapacitymap.com}}
      SMTP_NO_TLS: ${{SMTP_NO_TLS:-0}}
    configs:
      - source: intake_py
        target: /app/intake.py

configs:
  caddyfile:
    content: |
{block(caddyfile)}
  site_index:
    content: |
{block(index)}
  intake_py:
    content: |
{block(read("intake.py"))}

volumes:
  # Reuse the existing Caddy certificate store so the main domain keeps its HTTPS certificate.
  caddy_data:
    external: true
    name: ${{CADDY_DATA_VOLUME:-gratitude-wellness_caddy_data}}
  caddy_config:
"""
os.makedirs(os.path.join(HERE, "deploy"), exist_ok=True)
open(os.path.join(HERE, "deploy/docker-compose.yml"), "w", encoding="utf-8").write(compose)
print(f"deploy/docker-compose.yml: {len(compose)//1024} KB")
