from pathlib import Path
import json
import re

import openpyxl


ROOT = Path(__file__).resolve().parents[1]
SOURCE = Path(
    "/Users/charlesrobinson/Documents/Claude/Projects/Women NFP/EC_Map_Item_Bank_v1.0/ECMap_v1.1_Guided_Interview_64_Spine.xlsx"
)
OUT = ROOT / "src" / "spine.js"


THEME_BY_KERNEL = {
    "Activation": ["dimensional-framing", "narrative-intake"],
    "Sustained attention": ["dimensional-framing", "menopause-cognition"],
    "Working memory": ["dimensional-framing", "menopause-cognition"],
    "Prioritization": ["dimensional-framing"],
    "Time estimation": ["dimensional-framing"],
    "Task switching": ["dimensional-framing"],
    "Emotion under cognitive load": ["dimensional-framing", "menopause-specificity"],
    "Recovery after cognitive overload": ["menopause-specificity", "sleep-recovery"],
    "Sleep restoration": ["menopause-specificity", "sleep-recovery"],
    "Hormonal variability": ["menopause-specificity", "menopause-cognition"],
    "Energy stability": ["menopause-specificity"],
    "Stress physiology": ["dimensional-framing", "safety-referral"],
    "Glucose, appetite, and caffeine rhythm": ["menopause-specificity"],
    "Somatic burden": ["menopause-specificity"],
    "Medication, substance, and supplement effects": ["safety-referral"],
    "Recovery physiology": ["menopause-specificity", "sleep-recovery"],
}


def clean_text(value):
    if value is None:
        return None
    text = str(value)
    text = text.replace("\u2014", " - ")
    text = text.replace("\u2013", "-")
    text = text.replace("\u2018", "'").replace("\u2019", "'")
    text = text.replace("\u201c", '"').replace("\u201d", '"')
    text = text.replace("\u00a0", " ")
    text = re.sub(r"\s+", " ", text).strip()
    return text


def main():
    wb = openpyxl.load_workbook(SOURCE, read_only=True, data_only=True)
    ws = wb["v1.1_Scored_Spine"]
    headers = [cell.value for cell in ws[1]]
    items = []
    for row in ws.iter_rows(min_row=2, values_only=True):
        record = dict(zip(headers, row))
        item_id = record.get("Item ID")
        if not item_id:
            continue
        kernel = clean_text(record["Kernel"])
        private_item = clean_text(record.get("Private-clinical item"))
        enterprise_item = clean_text(record.get("Enterprise-safe item"))
        item = {
            "id": clean_text(item_id),
            "kernelId": clean_text(item_id).split("-")[0],
            "domain": "Cognition" if clean_text(item_id).startswith("C") else "Chemistry",
            "kernel": kernel,
            "function": clean_text(record["Function"]),
            "heuristic": clean_text(record["Binary heuristic"]),
            "prompt": private_item or enterprise_item,
            "enterprisePrompt": enterprise_item,
            "privatePrompt": private_item,
            "routing": clean_text(record["Layer routing"]),
            "evidenceThemes": THEME_BY_KERNEL.get(kernel, ["dimensional-framing"]),
        }
        items.append(item)

    js = (
        "// Generated by scripts/export_spine.py from the EC Map v1.1 64-item spine.\n"
        "// Do not edit item text here; update the source workbook and rerun npm run import:spine.\n\n"
        f"export const SPINE_ITEMS = {json.dumps(items, indent=2)};\n\n"
        "export const RESPONSE_SCALE = [\n"
        "  { value: 0, label: 'Never or almost never' },\n"
        "  { value: 1, label: 'Rarely' },\n"
        "  { value: 2, label: 'Sometimes' },\n"
        "  { value: 3, label: 'Often' },\n"
        "  { value: 4, label: 'Very often or almost always' }\n"
        "];\n\n"
        "export const CONTEXT_PROMPTS = [\n"
        "  { id: 'role_type', label: 'Current work or role pattern', type: 'choice', options: ['Heavy-output knowledge work', 'Leadership or management', 'Clinical/caregiving/front-line', 'Mixed creative and operational', 'Self-employed or portfolio', 'Out of paid work currently', 'Other'] },\n"
        "  { id: 'meeting_load', label: 'Weekly meeting and interruption load', type: 'choice', options: ['Under 5 hours', '5 to 15 hours', '15 to 25 hours', '25+ hours'] },\n"
        "  { id: 'sleep_stability', label: 'Sleep and wake timing across a typical week', type: 'choice', options: ['Very consistent', 'Mostly consistent', 'Variable', 'Highly disrupted'] },\n"
        "  { id: 'transition_context', label: 'Hormonal-transition context', type: 'choice', options: ['Cycling regularly', 'Cycling irregularly', 'Perimenopausal', 'Postmenopausal', 'On hormonal contraception', 'On menopausal hormone therapy', 'Prefer not to say'] },\n"
        "  { id: 'lifelong_attention_pattern', label: 'Attention and organization before midlife', type: 'choice', options: ['Longstanding since childhood or teen years', 'Present for many adult years', 'Mainly changed in midlife', 'Mainly appears under high stress', 'Unsure'] },\n"
        "  { id: 'setting_spread', label: 'Where the pattern shows up', type: 'choice', options: ['Across work, home, and relationships', 'Mostly at work', 'Mostly at home', 'Mostly during hormonal or sleep disruption', 'Only in unusual stress', 'Unsure'] },\n"
        "  { id: 'timeline', label: 'Compared with five years ago, current functional capacity is...', type: 'choice', options: ['Clearly better', 'About the same', 'Somewhat worse', 'Significantly worse', 'Has fluctuated'] }\n"
        "];\n\n"
        "export const NARRATIVE_PROMPTS = [\n"
        "  { id: 'compensating_for', label: 'What are you most tired of compensating for?' },\n"
        "  { id: 'public_private_cost', label: 'Where do you function well publicly but pay for it privately?' },\n"
        "  { id: 'capacity_shift', label: 'If your capacity increased by 25% next month, what would change first?' },\n"
        "  { id: 'what_helped', label: 'What have you already tried that helped, even briefly?' }\n"
        "];\n\n"
        "export const SAFETY_ITEMS = [\n"
        "  { id: 'S1', prompt: 'My sleep has been severely reduced lately, but my energy or mood has noticeably increased.', flag: 'Possible mania or hypomania pattern' },\n"
        "  { id: 'S2', prompt: 'My cognition has changed suddenly, severely, or in a way that feels medically unusual.', flag: 'Sudden or medically unusual cognitive change' },\n"
        "  { id: 'S3', prompt: 'I am using alcohol, cannabis, sedatives, stimulants, or supplements in ways that concern me or someone close to me.', flag: 'Substance, medication, or supplement concern' },\n"
        "  { id: 'S4', prompt: 'My functioning has declined to the point that my safety, basic self-care, or stability is at risk.', flag: 'Safety, self-care, or stability concern' }\n"
        "];\n"
    )
    OUT.write_text(js, encoding="utf-8")
    print(f"Wrote {len(items)} items to {OUT}")


if __name__ == "__main__":
    main()
