// Generated by scripts/export_spine.py from the EC Map v1.1 64-item spine.
// Do not edit item text here; update the source workbook and rerun npm run import:spine.

export const SPINE_ITEMS = [
  {
    "id": "C1-Sig",
    "kernelId": "C1",
    "domain": "Cognition",
    "kernel": "Activation",
    "function": "Signal",
    "heuristic": "Break vs not",
    "prompt": "When I know what to start, I still get stuck before the first action - even with time and quiet available.",
    "enterprisePrompt": "When I know what to start, I still get stuck before the first action - even with time and quiet available.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing",
      "narrative-intake"
    ]
  },
  {
    "id": "C1-Cost",
    "kernelId": "C1",
    "domain": "Cognition",
    "kernel": "Activation",
    "function": "Cost",
    "heuristic": "Impairment vs Inconvenience",
    "prompt": "Tasks I delayed starting this month became late, costly, or required visible apology or repair.",
    "enterprisePrompt": "Tasks I delayed starting this month became late, costly, or required visible apology or repair.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing",
      "narrative-intake"
    ]
  },
  {
    "id": "C1-Disc",
    "kernelId": "C1",
    "domain": "Cognition",
    "kernel": "Activation",
    "function": "Discriminator",
    "heuristic": "Trait vs State",
    "prompt": "Starting tasks feels hard across most days, not only when I am tired, in a low-hormone window, or under unusual stress.",
    "enterprisePrompt": "Getting started feels hard across most planned tasks - not only on bad-sleep, high-stress, or low-energy days.",
    "privatePrompt": "Starting tasks feels hard across most days, not only when I am tired, in a low-hormone window, or under unusual stress.",
    "routing": "Both - different versions",
    "evidenceThemes": [
      "dimensional-framing",
      "narrative-intake"
    ]
  },
  {
    "id": "C1-Mod",
    "kernelId": "C1",
    "domain": "Cognition",
    "kernel": "Activation",
    "function": "Modifiability",
    "heuristic": "Modifiable vs Stuck",
    "prompt": "External structure - a deadline, another person present, or a written first step - reliably gets me started when planning alone does not.",
    "enterprisePrompt": "External structure - a deadline, another person present, or a written first step - reliably gets me started when planning alone does not.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing",
      "narrative-intake"
    ]
  },
  {
    "id": "C2-Sig",
    "kernelId": "C2",
    "domain": "Cognition",
    "kernel": "Sustained attention",
    "function": "Signal",
    "heuristic": "Break vs not",
    "prompt": "During complex work, I lose the thread and need to reread, restart, or retrace my steps.",
    "enterprisePrompt": "During complex work, I lose the thread and need to reread, restart, or retrace my steps.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing",
      "menopause-cognition"
    ]
  },
  {
    "id": "C2-Cost",
    "kernelId": "C2",
    "domain": "Cognition",
    "kernel": "Sustained attention",
    "function": "Cost",
    "heuristic": "Impairment vs Inconvenience",
    "prompt": "Attention drift this month produced visible errors, missed information, or work I had to redo.",
    "enterprisePrompt": "Attention drift this month produced visible errors, missed information, or work I had to redo.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing",
      "menopause-cognition"
    ]
  },
  {
    "id": "C2-Disc",
    "kernelId": "C2",
    "domain": "Cognition",
    "kernel": "Sustained attention",
    "function": "Discriminator",
    "heuristic": "Trait vs State",
    "prompt": "My attention drifts on tasks I genuinely care about, not only on tasks that bore me.",
    "enterprisePrompt": "My attention drifts on tasks I genuinely care about, not only on tasks that bore me.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing",
      "menopause-cognition"
    ]
  },
  {
    "id": "C2-Mod",
    "kernelId": "C2",
    "domain": "Cognition",
    "kernel": "Sustained attention",
    "function": "Modifiability",
    "heuristic": "Modifiable vs Stuck",
    "prompt": "My attention holds noticeably better when I use external scaffolds rather than relying on effort alone.",
    "enterprisePrompt": "My attention holds noticeably better when I use external scaffolds rather than relying on effort alone.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing",
      "menopause-cognition"
    ]
  },
  {
    "id": "C3-Sig",
    "kernelId": "C3",
    "domain": "Cognition",
    "kernel": "Working memory",
    "function": "Signal",
    "heuristic": "Break vs not",
    "prompt": "Mid-sentence or mid-step, I lose the word, the number, or what I was about to do.",
    "enterprisePrompt": "Mid-sentence or mid-step, I lose the word, the number, or what I was about to do.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing",
      "menopause-cognition"
    ]
  },
  {
    "id": "C3-Cost",
    "kernelId": "C3",
    "domain": "Cognition",
    "kernel": "Working memory",
    "function": "Cost",
    "heuristic": "Impairment vs Inconvenience",
    "prompt": "Working-memory slips this month caused real errors at work or home, not just minor inconvenience.",
    "enterprisePrompt": "Working-memory slips this month caused real errors at work or home, not just minor inconvenience.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing",
      "menopause-cognition"
    ]
  },
  {
    "id": "C3-Disc",
    "kernelId": "C3",
    "domain": "Cognition",
    "kernel": "Working memory",
    "function": "Discriminator",
    "heuristic": "Trait vs State",
    "prompt": "These slips happen across rested days, after coffee, and during my best windows - not only when tired or sick.",
    "enterprisePrompt": "These slips happen across rested days, after coffee, and during my best windows - not only when tired or sick.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing",
      "menopause-cognition"
    ]
  },
  {
    "id": "C3-Mod",
    "kernelId": "C3",
    "domain": "Cognition",
    "kernel": "Working memory",
    "function": "Modifiability",
    "heuristic": "Modifiable vs Stuck",
    "prompt": "When I capture things outside my head - notes, voice memos, lists - I noticeably drop fewer details.",
    "enterprisePrompt": "When I capture things outside my head - notes, voice memos, lists - I noticeably drop fewer details.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing",
      "menopause-cognition"
    ]
  },
  {
    "id": "C4-Sig",
    "kernelId": "C4",
    "domain": "Cognition",
    "kernel": "Prioritization",
    "function": "Signal",
    "heuristic": "Break vs not",
    "prompt": "I see everything that needs doing but cannot decide what to do first, so I do nothing or the wrong thing.",
    "enterprisePrompt": "I see everything that needs doing but cannot decide what to do first, so I do nothing or the wrong thing.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C4-Cost",
    "kernelId": "C4",
    "domain": "Cognition",
    "kernel": "Prioritization",
    "function": "Cost",
    "heuristic": "Impairment vs Inconvenience",
    "prompt": "Prioritization breakdowns this month caused missed deadlines, dropped balls, or work on the wrong thing first.",
    "enterprisePrompt": "Prioritization breakdowns this month caused missed deadlines, dropped balls, or work on the wrong thing first.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C4-Disc",
    "kernelId": "C4",
    "domain": "Cognition",
    "kernel": "Prioritization",
    "function": "Discriminator",
    "heuristic": "Trait vs State",
    "prompt": "Even with a clear list and ranked priorities, the ordering itself still feels mentally costly.",
    "enterprisePrompt": "Even with a clear list and ranked priorities, the ordering itself still feels mentally costly.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C4-Mod",
    "kernelId": "C4",
    "domain": "Cognition",
    "kernel": "Prioritization",
    "function": "Modifiability",
    "heuristic": "Modifiable vs Stuck",
    "prompt": "I prioritize better when someone helps me triage out loud or when I limit choices to two.",
    "enterprisePrompt": "I prioritize better when someone helps me triage out loud or when I limit choices to two.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C5-Sig",
    "kernelId": "C5",
    "domain": "Cognition",
    "kernel": "Time estimation",
    "function": "Signal",
    "heuristic": "Break vs not",
    "prompt": "I consistently misjudge how long tasks take, even on work I have done many times before.",
    "enterprisePrompt": "I consistently misjudge how long tasks take, even on work I have done many times before.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C5-Cost",
    "kernelId": "C5",
    "domain": "Cognition",
    "kernel": "Time estimation",
    "function": "Cost",
    "heuristic": "Impairment vs Inconvenience",
    "prompt": "Time-estimation errors this month produced lateness, rushed quality, or missed commitments that other people noticed.",
    "enterprisePrompt": "Time-estimation errors this month produced lateness, rushed quality, or missed commitments that other people noticed.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C5-Disc",
    "kernelId": "C5",
    "domain": "Cognition",
    "kernel": "Time estimation",
    "function": "Discriminator",
    "heuristic": "Trait vs State",
    "prompt": "Time slips happen on familiar, well-practiced tasks too - not only on new or unusually complex ones.",
    "enterprisePrompt": "Time slips happen on familiar, well-practiced tasks too - not only on new or unusually complex ones.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C5-Mod",
    "kernelId": "C5",
    "domain": "Cognition",
    "kernel": "Time estimation",
    "function": "Modifiability",
    "heuristic": "Modifiable vs Stuck",
    "prompt": "External time anchors noticeably tighten my time estimates when I use them, more than self-discipline does.",
    "enterprisePrompt": "External time anchors noticeably tighten my time estimates when I use them, more than self-discipline does.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C6-Sig",
    "kernelId": "C6",
    "domain": "Cognition",
    "kernel": "Task switching",
    "function": "Signal",
    "heuristic": "Break vs not",
    "prompt": "Switching between tasks costs me disproportionate time and mental friction before I can re-engage.",
    "enterprisePrompt": "Switching between tasks costs me disproportionate time and mental friction before I can re-engage.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C6-Cost",
    "kernelId": "C6",
    "domain": "Cognition",
    "kernel": "Task switching",
    "function": "Cost",
    "heuristic": "Impairment vs Inconvenience",
    "prompt": "Interruptions and switches this month visibly degraded the quality or completeness of my work.",
    "enterprisePrompt": "Interruptions and switches this month visibly degraded the quality or completeness of my work.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C6-Disc",
    "kernelId": "C6",
    "domain": "Cognition",
    "kernel": "Task switching",
    "function": "Discriminator",
    "heuristic": "Trait vs State",
    "prompt": "Switching costs stay high even between similar tasks I do every week, not only between unfamiliar ones.",
    "enterprisePrompt": "Switching costs stay high even between similar tasks I do every week, not only between unfamiliar ones.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C6-Mod",
    "kernelId": "C6",
    "domain": "Cognition",
    "kernel": "Task switching",
    "function": "Modifiability",
    "heuristic": "Modifiable vs Stuck",
    "prompt": "Protected uninterrupted blocks of an hour or more noticeably improve my output when I can actually claim them.",
    "enterprisePrompt": "Protected uninterrupted blocks of an hour or more noticeably improve my output when I can actually claim them.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C7-Sig",
    "kernelId": "C7",
    "domain": "Cognition",
    "kernel": "Emotion regulation under load",
    "function": "Signal",
    "heuristic": "Break vs not",
    "prompt": "When mental demand spikes, my emotional reactions intensify - irritation, tearfulness, or shutdown - beyond what the moment calls for.",
    "enterprisePrompt": "When mental demand spikes, my emotional reactions intensify - irritation, tearfulness, or shutdown - beyond what the moment calls for.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C7-Cost",
    "kernelId": "C7",
    "domain": "Cognition",
    "kernel": "Emotion regulation under load",
    "function": "Cost",
    "heuristic": "Impairment vs Inconvenience",
    "prompt": "Tipping over emotionally this month cost me a conversation, a relationship, or work I cared about.",
    "enterprisePrompt": "Tipping over emotionally this month cost me a conversation, a relationship, or work I cared about.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C7-Disc",
    "kernelId": "C7",
    "domain": "Cognition",
    "kernel": "Emotion regulation under load",
    "function": "Discriminator",
    "heuristic": "Trait vs State",
    "prompt": "Cognitive load triggers these reactions even when I am rested, fed, and not in a hormonally vulnerable window.",
    "enterprisePrompt": "Cognitive load triggers these reactions even when I am rested, fed, and not having a hard body day.",
    "privatePrompt": "Cognitive load triggers these reactions even when I am rested, fed, and not in a hormonally vulnerable window.",
    "routing": "Both - different versions",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C7-Mod",
    "kernelId": "C7",
    "domain": "Cognition",
    "kernel": "Emotion regulation under load",
    "function": "Modifiability",
    "heuristic": "Modifiable vs Stuck",
    "prompt": "Pausing, stepping away briefly, or naming the load out loud reliably brings the reaction back down.",
    "enterprisePrompt": "Pausing, stepping away briefly, or naming the load out loud reliably brings the reaction back down.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C8-Sig",
    "kernelId": "C8",
    "domain": "Cognition",
    "kernel": "Recovery after cog overload",
    "function": "Signal",
    "heuristic": "Break vs not",
    "prompt": "After mentally demanding days, I need more downtime than usual before I can think clearly again.",
    "enterprisePrompt": "After mentally demanding days, I need more downtime than usual before I can think clearly again.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C8-Cost",
    "kernelId": "C8",
    "domain": "Cognition",
    "kernel": "Recovery after cog overload",
    "function": "Cost",
    "heuristic": "Impairment vs Inconvenience",
    "prompt": "Slow recovery this month meant cancelling, withdrawing, or under-functioning the day after a demanding day.",
    "enterprisePrompt": "Slow recovery this month meant cancelling, withdrawing, or under-functioning the day after a demanding day.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C8-Disc",
    "kernelId": "C8",
    "domain": "Cognition",
    "kernel": "Recovery after cog overload",
    "function": "Discriminator",
    "heuristic": "Trait vs State (chemistry/drift-led)",
    "prompt": "Recovery time has lengthened compared with my prior baseline at the same workload, not only after exceptional weeks.",
    "enterprisePrompt": "Recovery time has lengthened compared with my prior baseline at the same workload, not only after exceptional weeks.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C8-Mod",
    "kernelId": "C8",
    "domain": "Cognition",
    "kernel": "Recovery after cog overload",
    "function": "Modifiability",
    "heuristic": "Modifiable vs Stuck",
    "prompt": "Deliberate recovery - protecting sleep, quieter evenings, real off-time - noticeably shortens how long I feel depleted.",
    "enterprisePrompt": "Deliberate recovery - protecting sleep, quieter evenings, real off-time - noticeably shortens how long I feel depleted.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "H1-Sig",
    "kernelId": "H1",
    "domain": "Chemistry",
    "kernel": "Sleep restoration",
    "function": "Signal",
    "heuristic": "Break vs not",
    "prompt": "Even with adequate hours, I wake unrested or take a long time to feel mentally online.",
    "enterprisePrompt": "Even with adequate hours, I wake unrested or take a long time to feel mentally online.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "menopause-specificity",
      "sleep-recovery"
    ]
  },
  {
    "id": "H1-Cost",
    "kernelId": "H1",
    "domain": "Chemistry",
    "kernel": "Sleep restoration",
    "function": "Cost",
    "heuristic": "Impairment vs Inconvenience",
    "prompt": "Poor sleep restoration this month measurably degraded my work, mood, or judgment within 24-48 hours.",
    "enterprisePrompt": "Poor sleep restoration this month measurably degraded my work, mood, or judgment within 24-48 hours.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "menopause-specificity",
      "sleep-recovery"
    ]
  },
  {
    "id": "H1-Disc",
    "kernelId": "H1",
    "domain": "Chemistry",
    "kernel": "Sleep restoration",
    "function": "Discriminator",
    "heuristic": "Trait vs State (chemistry-led)",
    "prompt": "Sleep quality varies with physical factors - heat, night sweats, racing body, alcohol, late caffeine - not only with thoughts.",
    "enterprisePrompt": "My sleep quality is driven more by physical factors I notice in my body than by what is on my mind.",
    "privatePrompt": "Sleep quality varies with physical factors - heat, night sweats, racing body, alcohol, late caffeine - not only with thoughts.",
    "routing": "Both - different versions",
    "evidenceThemes": [
      "menopause-specificity",
      "sleep-recovery"
    ]
  },
  {
    "id": "H1-Mod",
    "kernelId": "H1",
    "domain": "Chemistry",
    "kernel": "Sleep restoration",
    "function": "Modifiability",
    "heuristic": "Modifiable vs Stuck",
    "prompt": "When I protect sleep deliberately for several nights in a row, my daytime cognition and mood improve noticeably.",
    "enterprisePrompt": "When I protect sleep deliberately for several nights in a row, my daytime cognition and mood improve noticeably.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "menopause-specificity",
      "sleep-recovery"
    ]
  },
  {
    "id": "H2-Sig",
    "kernelId": "H2",
    "domain": "Chemistry",
    "kernel": "Hormonal variability",
    "function": "Signal",
    "heuristic": "Break vs not",
    "prompt": "My cognition, mood, or energy shifts in a pattern I can feel but cannot fully predict.",
    "enterprisePrompt": "My cognition, mood, or energy shifts in a pattern I can feel but cannot fully predict.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "menopause-specificity",
      "menopause-cognition"
    ]
  },
  {
    "id": "H2-Cost",
    "kernelId": "H2",
    "domain": "Chemistry",
    "kernel": "Hormonal variability",
    "function": "Cost",
    "heuristic": "Impairment vs Inconvenience",
    "prompt": "Hormonal-pattern shifts this month produced days I could not perform at my usual baseline.",
    "enterprisePrompt": "Predictable low-capacity windows this month included days I could not perform at my usual baseline.",
    "privatePrompt": "Hormonal-pattern shifts this month produced days I could not perform at my usual baseline.",
    "routing": "Both - different versions",
    "evidenceThemes": [
      "menopause-specificity",
      "menopause-cognition"
    ]
  },
  {
    "id": "H2-Disc",
    "kernelId": "H2",
    "domain": "Chemistry",
    "kernel": "Hormonal variability",
    "function": "Discriminator",
    "heuristic": "Trait vs State (chemistry-led)",
    "prompt": "These shifts track with cycle timing, perimenopausal changes, or hormone transitions more than with workload or sleep alone.",
    "enterprisePrompt": "These shifts track with predictable bodily patterns more than with workload or sleep alone.",
    "privatePrompt": "These shifts track with cycle timing, perimenopausal changes, or hormone transitions more than with workload or sleep alone.",
    "routing": "Both - different versions",
    "evidenceThemes": [
      "menopause-specificity",
      "menopause-cognition"
    ]
  },
  {
    "id": "H2-Mod",
    "kernelId": "H2",
    "domain": "Chemistry",
    "kernel": "Hormonal variability",
    "function": "Modifiability",
    "heuristic": "Modifiable vs Stuck",
    "prompt": "Tracking the pattern and planning lighter demand into low windows reliably reduces the cost.",
    "enterprisePrompt": "Tracking the pattern and planning lighter demand into low windows reliably reduces the cost.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "menopause-specificity",
      "menopause-cognition"
    ]
  },
  {
    "id": "H3-Sig",
    "kernelId": "H3",
    "domain": "Chemistry",
    "kernel": "Energy stability",
    "function": "Signal",
    "heuristic": "Break vs not",
    "prompt": "My energy is unpredictable across the day - strong stretches followed by abrupt drops without clear cause.",
    "enterprisePrompt": "My energy is unpredictable across the day - strong stretches followed by abrupt drops without clear cause.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "menopause-specificity"
    ]
  },
  {
    "id": "H3-Cost",
    "kernelId": "H3",
    "domain": "Chemistry",
    "kernel": "Energy stability",
    "function": "Cost",
    "heuristic": "Impairment vs Inconvenience",
    "prompt": "Energy crashes this month forced me to cancel, postpone, or under-deliver on plans that mattered.",
    "enterprisePrompt": "Energy crashes this month forced me to cancel, postpone, or under-deliver on plans that mattered.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "menopause-specificity"
    ]
  },
  {
    "id": "H3-Disc",
    "kernelId": "H3",
    "domain": "Chemistry",
    "kernel": "Energy stability",
    "function": "Discriminator",
    "heuristic": "Trait vs State (chemistry-led)",
    "prompt": "Crashes happen on days with adequate sleep, food, and reasonable demand - not only on overloaded days.",
    "enterprisePrompt": "Crashes happen on days with adequate sleep, food, and reasonable demand - not only on overloaded days.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "menopause-specificity"
    ]
  },
  {
    "id": "H3-Mod",
    "kernelId": "H3",
    "domain": "Chemistry",
    "kernel": "Energy stability",
    "function": "Modifiability",
    "heuristic": "Modifiable vs Stuck",
    "prompt": "When I pace effort, eat regularly, and use short rest blocks, my energy steadies noticeably.",
    "enterprisePrompt": "When I pace effort, eat regularly, and use short rest blocks, my energy steadies noticeably.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "menopause-specificity"
    ]
  },
  {
    "id": "H4-Sig",
    "kernelId": "H4",
    "domain": "Chemistry",
    "kernel": "Stress physiology",
    "function": "Signal",
    "heuristic": "Break vs not",
    "prompt": "My body stays revved up after stress passes - restless, tense, or wired-but-tired even when the trigger is over.",
    "enterprisePrompt": "My body stays revved up after stress passes - restless, tense, or wired-but-tired even when the trigger is over.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing",
      "safety-referral"
    ]
  },
  {
    "id": "H4-Cost",
    "kernelId": "H4",
    "domain": "Chemistry",
    "kernel": "Stress physiology",
    "function": "Cost",
    "heuristic": "Impairment vs Inconvenience",
    "prompt": "Staying revved up after stress this month interfered with my sleep, focus, digestion, or ability to enjoy downtime.",
    "enterprisePrompt": "Staying revved up after stress this month interfered with my sleep, focus, digestion, or ability to enjoy downtime.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing",
      "safety-referral"
    ]
  },
  {
    "id": "H4-Disc",
    "kernelId": "H4",
    "domain": "Chemistry",
    "kernel": "Stress physiology",
    "function": "Discriminator",
    "heuristic": "Trait vs State (chemistry/threat-led)",
    "prompt": "My body revs up even at small or imagined stressors, not only during genuinely demanding events.",
    "enterprisePrompt": "My body revs up even at small or imagined stressors, not only during genuinely demanding events.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing",
      "safety-referral"
    ]
  },
  {
    "id": "H4-Mod",
    "kernelId": "H4",
    "domain": "Chemistry",
    "kernel": "Stress physiology",
    "function": "Modifiability",
    "heuristic": "Modifiable vs Stuck",
    "prompt": "Calming practices - breath, movement, time outside - reliably bring my body back down when I use them.",
    "enterprisePrompt": "Calming practices - breath, movement, time outside - reliably bring my body back down when I use them.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing",
      "safety-referral"
    ]
  },
  {
    "id": "H5-Sig",
    "kernelId": "H5",
    "domain": "Chemistry",
    "kernel": "Glucose/appetite/caffeine rhythm",
    "function": "Signal",
    "heuristic": "Break vs not",
    "prompt": "Skipped meals or mistimed caffeine visibly destabilize my focus, mood, or energy within hours.",
    "enterprisePrompt": "Skipped meals or mistimed caffeine visibly destabilize my focus, mood, or energy within hours.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "H5-Cost",
    "kernelId": "H5",
    "domain": "Chemistry",
    "kernel": "Glucose/appetite/caffeine rhythm",
    "function": "Cost",
    "heuristic": "Impairment vs Inconvenience",
    "prompt": "Missing meals or mistiming caffeine this month produced crashes, irritability, or scattered thinking that disrupted my day.",
    "enterprisePrompt": "Missing meals or mistiming caffeine this month produced crashes, irritability, or scattered thinking that disrupted my day.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "H5-Disc",
    "kernelId": "H5",
    "domain": "Chemistry",
    "kernel": "Glucose/appetite/caffeine rhythm",
    "function": "Discriminator",
    "heuristic": "Trait vs State (chemistry-led)",
    "prompt": "Stabilizing protein, water, and caffeine timing changes my capacity more reliably than effort or mindset does.",
    "enterprisePrompt": "Stabilizing protein, water, and caffeine timing changes my capacity more reliably than effort or mindset does.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "H5-Mod",
    "kernelId": "H5",
    "domain": "Chemistry",
    "kernel": "Glucose/appetite/caffeine rhythm",
    "function": "Modifiability",
    "heuristic": "Modifiable vs Stuck",
    "prompt": "When I keep regular meals and caffeine before noon, I notice steadier focus and mood across the day.",
    "enterprisePrompt": "When I keep regular meals and caffeine before noon, I notice steadier focus and mood across the day.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "H6-Sig",
    "kernelId": "H6",
    "domain": "Chemistry",
    "kernel": "Somatic burden",
    "function": "Signal",
    "heuristic": "Break vs not",
    "prompt": "Pain, headaches, gut symptoms, or body tension consume background attention and interfere with thinking or work.",
    "enterprisePrompt": "Pain, headaches, gut symptoms, or body tension consume background attention and interfere with thinking or work.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "menopause-specificity"
    ]
  },
  {
    "id": "H6-Cost",
    "kernelId": "H6",
    "domain": "Chemistry",
    "kernel": "Somatic burden",
    "function": "Cost",
    "heuristic": "Impairment vs Inconvenience",
    "prompt": "Body-based symptoms this month forced me to drop tasks, leave events early, or visibly compensate.",
    "enterprisePrompt": "Body-based symptoms this month forced me to drop tasks, leave events early, or visibly compensate.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "menopause-specificity"
    ]
  },
  {
    "id": "H6-Disc",
    "kernelId": "H6",
    "domain": "Chemistry",
    "kernel": "Somatic burden",
    "function": "Discriminator",
    "heuristic": "Trait vs State (chemistry-led)",
    "prompt": "These symptoms appear or worsen with hormonal shifts, sleep loss, or autonomic load - not only after injury or exertion.",
    "enterprisePrompt": "These symptoms appear or worsen with predictable bodily patterns and poor sleep - not only after injury or exertion.",
    "privatePrompt": "These symptoms appear or worsen with hormonal shifts, sleep loss, or autonomic load - not only after injury or exertion.",
    "routing": "Both - different versions",
    "evidenceThemes": [
      "menopause-specificity"
    ]
  },
  {
    "id": "H6-Mod",
    "kernelId": "H6",
    "domain": "Chemistry",
    "kernel": "Somatic burden",
    "function": "Modifiability",
    "heuristic": "Modifiable vs Stuck",
    "prompt": "Consistent physical care - hydration, sleep, movement, treatment - reliably reduces these body symptoms when I prioritize it.",
    "enterprisePrompt": "Consistent physical care - hydration, sleep, movement, treatment - reliably reduces these body symptoms when I prioritize it.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "menopause-specificity"
    ]
  },
  {
    "id": "H7-Sig",
    "kernelId": "H7",
    "domain": "Chemistry",
    "kernel": "Medication/substance/supplement",
    "function": "Signal",
    "heuristic": "Break vs not",
    "prompt": "Something I take or use - prescription, supplement, alcohol, cannabis, or caffeine - clearly shifts my cognition or mood.",
    "enterprisePrompt": "Something I take or use clearly shifts my focus, mood, or energy.",
    "privatePrompt": "Something I take or use - prescription, supplement, alcohol, cannabis, or caffeine - clearly shifts my cognition or mood.",
    "routing": "Both - different versions",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "H7-Cost",
    "kernelId": "H7",
    "domain": "Chemistry",
    "kernel": "Medication/substance/supplement",
    "function": "Cost",
    "heuristic": "Impairment vs Inconvenience",
    "prompt": "Substance or medication effects this month caused side effects, rebound, or capacity drops I had to manage around.",
    "enterprisePrompt": null,
    "privatePrompt": "Substance or medication effects this month caused side effects, rebound, or capacity drops I had to manage around.",
    "routing": "Private only",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "H7-Disc",
    "kernelId": "H7",
    "domain": "Chemistry",
    "kernel": "Medication/substance/supplement",
    "function": "Discriminator",
    "heuristic": "Trait vs State (chemistry-led)",
    "prompt": "Capacity changes track with what I am taking or using more than with workload or relationships.",
    "enterprisePrompt": null,
    "privatePrompt": "Capacity changes track with what I am taking or using more than with workload or relationships.",
    "routing": "Private only",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "H7-Mod",
    "kernelId": "H7",
    "domain": "Chemistry",
    "kernel": "Medication/substance/supplement",
    "function": "Modifiability",
    "heuristic": "Modifiable vs Stuck",
    "prompt": "Adjusting timing, dose, or use pattern reliably changes my capacity when I make the change deliberately.",
    "enterprisePrompt": null,
    "privatePrompt": "Adjusting timing, dose, or use pattern reliably changes my capacity when I make the change deliberately.",
    "routing": "Private only",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "H8-Sig",
    "kernelId": "H8",
    "domain": "Chemistry",
    "kernel": "Recovery physiology",
    "function": "Signal",
    "heuristic": "Break vs not",
    "prompt": "After ordinary effort or a busy week, my body takes longer to recover than it used to.",
    "enterprisePrompt": "After ordinary effort or a busy week, my body takes longer to recover than it used to.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "menopause-specificity",
      "sleep-recovery"
    ]
  },
  {
    "id": "H8-Cost",
    "kernelId": "H8",
    "domain": "Chemistry",
    "kernel": "Recovery physiology",
    "function": "Cost",
    "heuristic": "Impairment vs Inconvenience",
    "prompt": "Slow physical recovery this month meant cancelled plans, lost weekends, or under-functioning at work.",
    "enterprisePrompt": "Slow physical recovery this month meant cancelled plans, lost weekends, or under-functioning at work.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "menopause-specificity",
      "sleep-recovery"
    ]
  },
  {
    "id": "H8-Disc",
    "kernelId": "H8",
    "domain": "Chemistry",
    "kernel": "Recovery physiology",
    "function": "Discriminator",
    "heuristic": "Trait vs State (chemistry/drift-led)",
    "prompt": "Recovery has slowed compared with my prior baseline at the same workload - not only after exceptional weeks.",
    "enterprisePrompt": "Recovery has slowed compared with my prior baseline at the same workload - not only after exceptional weeks.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "menopause-specificity",
      "sleep-recovery"
    ]
  },
  {
    "id": "H8-Mod",
    "kernelId": "H8",
    "domain": "Chemistry",
    "kernel": "Recovery physiology",
    "function": "Modifiability",
    "heuristic": "Modifiable vs Stuck",
    "prompt": "Deliberate recovery - protecting sleep, hydration, quieter downtime - noticeably shortens how long I feel depleted.",
    "enterprisePrompt": "Deliberate recovery - protecting sleep, hydration, quieter downtime - noticeably shortens how long I feel depleted.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "menopause-specificity",
      "sleep-recovery"
    ]
  }
];

export const RESPONSE_SCALE = [
  { value: 0, label: 'Never or almost never' },
  { value: 1, label: 'Rarely' },
  { value: 2, label: 'Sometimes' },
  { value: 3, label: 'Often' },
  { value: 4, label: 'Very often or almost always' }
];

export const CONTEXT_PROMPTS = [
  { id: 'role_type', label: 'Current work or role pattern', type: 'choice', options: ['Heavy-output knowledge work', 'Leadership or management', 'Clinical/caregiving/front-line', 'Mixed creative and operational', 'Self-employed or portfolio', 'Out of paid work currently', 'Other'] },
  { id: 'meeting_load', label: 'Weekly meeting and interruption load', type: 'choice', options: ['Under 5 hours', '5 to 15 hours', '15 to 25 hours', '25+ hours'] },
  { id: 'sleep_stability', label: 'Sleep and wake timing across a typical week', type: 'choice', options: ['Very consistent', 'Mostly consistent', 'Variable', 'Highly disrupted'] },
  { id: 'transition_context', label: 'Hormonal-transition context', type: 'choice', options: ['Cycling regularly', 'Cycling irregularly', 'Perimenopausal', 'Postmenopausal', 'On hormonal contraception', 'On menopausal hormone therapy', 'Prefer not to say'] },
  { id: 'lifelong_attention_pattern', label: 'Attention and organization before midlife', type: 'choice', options: ['Longstanding since childhood or teen years', 'Present for many adult years', 'Mainly changed in midlife', 'Mainly appears under high stress', 'Unsure'] },
  { id: 'setting_spread', label: 'Where the pattern shows up', type: 'choice', options: ['Across work, home, and relationships', 'Mostly at work', 'Mostly at home', 'Mostly during hormonal or sleep disruption', 'Only in unusual stress', 'Unsure'] },
  { id: 'timeline', label: 'Compared with five years ago, current functional capacity is...', type: 'choice', options: ['Clearly better', 'About the same', 'Somewhat worse', 'Significantly worse', 'Has fluctuated'] }
];

export const NARRATIVE_PROMPTS = [
  { id: 'compensating_for', label: 'What are you most tired of compensating for?' },
  { id: 'public_private_cost', label: 'Where do you function well publicly but pay for it privately?' },
  { id: 'capacity_shift', label: 'If your capacity increased by 25% next month, what would change first?' },
  { id: 'what_helped', label: 'What have you already tried that helped, even briefly?' }
];

export const SAFETY_ITEMS = [
  { id: 'S1', prompt: 'My sleep has been severely reduced lately, but my energy or mood has noticeably increased.', flag: 'Possible mania or hypomania pattern' },
  { id: 'S2', prompt: 'My cognition has changed suddenly, severely, or in a way that feels medically unusual.', flag: 'Sudden or medically unusual cognitive change' },
  { id: 'S3', prompt: 'I am using alcohol, cannabis, sedatives, stimulants, or supplements in ways that concern me or someone close to me.', flag: 'Substance, medication, or supplement concern' },
  { id: 'S4', prompt: 'My functioning has declined to the point that my safety, basic self-care, or stability is at risk.', flag: 'Safety, self-care, or stability concern' }
];
