// Generated by scripts/export_spine.py from the EC Map v1.1 64-item spine.
// Do not edit item text here; update the source workbook and rerun npm run import:spine.

import { SpineItem, ResponseScaleOption, ContextPrompt, NarrativePrompt, SafetyItem } from "./types.js";

export const SPINE_ITEMS: SpineItem[] = [
  {
    "id": "C1-Sig",
    "kernelId": "C1",
    "domain": "Cognition",
    "kernel": "Activation",
    "function": "Signal",
    "heuristic": "Break vs not",
    "prompt": "When I know what to start, I still get stuck before the first action - even with time and quiet available.",
    "enterprisePrompt": "When I know what to start, I still get stuck before the first action - even with time and quiet available.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing",
      "narrative-intake"
    ]
  },
  {
    "id": "C1-Cost",
    "kernelId": "C1",
    "domain": "Cognition",
    "kernel": "Activation",
    "function": "Cost",
    "heuristic": "Impairment vs Inconvenience",
    "prompt": "Tasks I delayed starting this month became late, costly, or required visible apology or repair.",
    "enterprisePrompt": "Tasks I delayed starting this month became late, costly, or required visible apology or repair.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing",
      "narrative-intake"
    ]
  },
  {
    "id": "C1-Disc",
    "kernelId": "C1",
    "domain": "Cognition",
    "kernel": "Activation",
    "function": "Discriminator",
    "heuristic": "Trait vs State",
    "prompt": "Getting started is hard on ordinary rested days too, not only during poor sleep, illness, high stress, or unusually heavy demand.",
    "enterprisePrompt": "Getting started is hard on ordinary rested days too, not only during poor sleep, illness, high stress, or unusually heavy demand.",
    "privatePrompt": "Getting started is hard on ordinary rested days too, not only during poor sleep, illness, high stress, or unusually heavy demand.",
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing",
      "narrative-intake"
    ]
  },
  {
    "id": "C1-Mod",
    "kernelId": "C1",
    "domain": "Cognition",
    "kernel": "Activation",
    "function": "Modifiability",
    "heuristic": "Modifiable vs Stuck",
    "prompt": "External structure - a deadline, another person present, or a written first step - reliably gets me started when planning alone does not.",
    "enterprisePrompt": "External structure - a deadline, another person present, or a written first step - reliably gets me started when planning alone does not.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing",
      "narrative-intake"
    ]
  },
  {
    "id": "C2-Sig",
    "kernelId": "C2",
    "domain": "Cognition",
    "kernel": "Sustained attention",
    "function": "Signal",
    "heuristic": "Break vs not",
    "prompt": "During complex work, I lose the thread and need to reread, restart, or retrace my steps.",
    "enterprisePrompt": "During complex work, I lose the thread and need to reread, restart, or retrace my steps.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing",
      "menopause-cognition"
    ]
  },
  {
    "id": "C2-Cost",
    "kernelId": "C2",
    "domain": "Cognition",
    "kernel": "Sustained attention",
    "function": "Cost",
    "heuristic": "Impairment vs Inconvenience",
    "prompt": "Attention drift this month produced visible errors, missed information, or work I had to redo.",
    "enterprisePrompt": "Attention drift this month produced visible errors, missed information, or work I had to redo.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing",
      "menopause-cognition"
    ]
  },
  {
    "id": "C2-Disc",
    "kernelId": "C2",
    "domain": "Cognition",
    "kernel": "Sustained attention",
    "function": "Discriminator",
    "heuristic": "Trait vs State",
    "prompt": "My attention drifts on tasks I genuinely care about, not only on tasks that bore me.",
    "enterprisePrompt": "My attention drifts on tasks I genuinely care about, not only on tasks that bore me.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing",
      "menopause-cognition"
    ]
  },
  {
    "id": "C2-Mod",
    "kernelId": "C2",
    "domain": "Cognition",
    "kernel": "Sustained attention",
    "function": "Modifiability",
    "heuristic": "Modifiable vs Stuck",
    "prompt": "My attention holds noticeably better when I use external scaffolds rather than relying on effort alone.",
    "enterprisePrompt": "My attention holds noticeably better when I use external scaffolds rather than relying on effort alone.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing",
      "menopause-cognition"
    ]
  },
  {
    "id": "C3-Sig",
    "kernelId": "C3",
    "domain": "Cognition",
    "kernel": "Working memory",
    "function": "Signal",
    "heuristic": "Break vs not",
    "prompt": "In the middle of speaking or doing a task, I lose the exact word, number, instruction, or next step I was holding.",
    "enterprisePrompt": "In the middle of speaking or doing a task, I lose the exact word, number, instruction, or next step I was holding.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing",
      "menopause-cognition"
    ]
  },
  {
    "id": "C3-Cost",
    "kernelId": "C3",
    "domain": "Cognition",
    "kernel": "Working memory",
    "function": "Cost",
    "heuristic": "Impairment vs Inconvenience",
    "prompt": "This past month, losing information from mind led to concrete mistakes, repeated work, missed details, or avoidable follow-up.",
    "enterprisePrompt": "This past month, losing information from mind led to concrete mistakes, repeated work, missed details, or avoidable follow-up.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing",
      "menopause-cognition"
    ]
  },
  {
    "id": "C3-Disc",
    "kernelId": "C3",
    "domain": "Cognition",
    "kernel": "Working memory",
    "function": "Discriminator",
    "heuristic": "Trait vs State",
    "prompt": "Memory gaps show up even on rested, ordinary-demand days, not only when sleep, illness, stress, or overload would explain them.",
    "enterprisePrompt": "Memory gaps show up even on rested, ordinary-demand days, not only when sleep, illness, stress, or overload would explain them.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing",
      "menopause-cognition"
    ]
  },
  {
    "id": "C3-Mod",
    "kernelId": "C3",
    "domain": "Cognition",
    "kernel": "Working memory",
    "function": "Modifiability",
    "heuristic": "Modifiable vs Stuck",
    "prompt": "A capture system only helps if I use it immediately; if I wait, details often disappear before I can record them.",
    "enterprisePrompt": "A capture system only helps if I use it immediately; if I wait, details often disappear before I can record them.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing",
      "menopause-cognition"
    ]
  },
  {
    "id": "C4-Sig",
    "kernelId": "C4",
    "domain": "Cognition",
    "kernel": "Prioritization",
    "function": "Signal",
    "heuristic": "Break vs not",
    "prompt": "I see everything that needs doing but cannot decide what to do first, so I do nothing or the wrong thing.",
    "enterprisePrompt": "I see everything that needs doing but cannot decide what to do first, so I do nothing or the wrong thing.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C4-Cost",
    "kernelId": "C4",
    "domain": "Cognition",
    "kernel": "Prioritization",
    "function": "Cost",
    "heuristic": "Impairment vs Inconvenience",
    "prompt": "Prioritization breakdowns this month caused missed deadlines, dropped balls, or work on the wrong thing first.",
    "enterprisePrompt": "Prioritization breakdowns this month caused missed deadlines, dropped balls, or work on the wrong thing first.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C4-Disc",
    "kernelId": "C4",
    "domain": "Cognition",
    "kernel": "Prioritization",
    "function": "Discriminator",
    "heuristic": "Trait vs State",
    "prompt": "Even with a clear list and ranked priorities, the ordering itself still feels mentally costly.",
    "enterprisePrompt": "Even with a clear list and ranked priorities, the ordering itself still feels mentally costly.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C4-Mod",
    "kernelId": "C4",
    "domain": "Cognition",
    "kernel": "Prioritization",
    "function": "Modifiability",
    "heuristic": "Modifiable vs Stuck",
    "prompt": "I prioritize better when someone helps me triage out loud or when I limit choices to two.",
    "enterprisePrompt": "I prioritize better when someone helps me triage out loud or when I limit choices to two.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C5-Sig",
    "kernelId": "C5",
    "domain": "Cognition",
    "kernel": "Time estimation",
    "function": "Signal",
    "heuristic": "Break vs not",
    "prompt": "I consistently misjudge how long tasks take, even on work I have done many times before.",
    "enterprisePrompt": "I consistently misjudge how long tasks take, even on work I have done many times before.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C5-Cost",
    "kernelId": "C5",
    "domain": "Cognition",
    "kernel": "Time estimation",
    "function": "Cost",
    "heuristic": "Impairment vs Inconvenience",
    "prompt": "Time-estimation errors this month produced lateness, rushed quality, or missed commitments that other people noticed.",
    "enterprisePrompt": "Time-estimation errors this month produced lateness, rushed quality, or missed commitments that other people noticed.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C5-Disc",
    "kernelId": "C5",
    "domain": "Cognition",
    "kernel": "Time estimation",
    "function": "Discriminator",
    "heuristic": "Trait vs State",
    "prompt": "Time slips happen on familiar, well-practiced tasks too - not only on new or unusually complex ones.",
    "enterprisePrompt": "Time slips happen on familiar, well-practiced tasks too - not only on new or unusually complex ones.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C5-Mod",
    "kernelId": "C5",
    "domain": "Cognition",
    "kernel": "Time estimation",
    "function": "Modifiability",
    "heuristic": "Modifiable vs Stuck",
    "prompt": "External time anchors noticeably tighten my time estimates when I use them, more than self-discipline does.",
    "enterprisePrompt": "External time anchors noticeably tighten my time estimates when I use them, more than self-discipline does.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C6-Sig",
    "kernelId": "C6",
    "domain": "Cognition",
    "kernel": "Task switching",
    "function": "Signal",
    "heuristic": "Break vs not",
    "prompt": "Switching between tasks costs me disproportionate time and mental friction before I can re-engage.",
    "enterprisePrompt": "Switching between tasks costs me disproportionate time and mental friction before I can re-engage.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C6-Cost",
    "kernelId": "C6",
    "domain": "Cognition",
    "kernel": "Task switching",
    "function": "Cost",
    "heuristic": "Impairment vs Inconvenience",
    "prompt": "This past month, interruptions made me lose work state enough that I missed steps, duplicated work, or left tasks unfinished.",
    "enterprisePrompt": "This past month, interruptions made me lose work state enough that I missed steps, duplicated work, or left tasks unfinished.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C6-Disc",
    "kernelId": "C6",
    "domain": "Cognition",
    "kernel": "Task switching",
    "function": "Discriminator",
    "heuristic": "Trait vs State",
    "prompt": "Even planned switches between familiar tasks leave a restart cost before I can think clearly again.",
    "enterprisePrompt": "Even planned switches between familiar tasks leave a restart cost before I can think clearly again.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C6-Mod",
    "kernelId": "C6",
    "domain": "Cognition",
    "kernel": "Task switching",
    "function": "Modifiability",
    "heuristic": "Modifiable vs Stuck",
    "prompt": "Batching similar tasks or using a short transition ritual reduces restart cost more reliably than simply trying harder.",
    "enterprisePrompt": "Batching similar tasks or using a short transition ritual reduces restart cost more reliably than simply trying harder.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C7-Sig",
    "kernelId": "C7",
    "domain": "Cognition",
    "kernel": "Emotion regulation under load",
    "function": "Signal",
    "heuristic": "Break vs not",
    "prompt": "When mental demand spikes, my emotional reactions intensify - irritation, tearfulness, or shutdown - beyond what the moment calls for.",
    "enterprisePrompt": "When mental demand spikes, my emotional reactions intensify - irritation, tearfulness, or shutdown - beyond what the moment calls for.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C7-Cost",
    "kernelId": "C7",
    "domain": "Cognition",
    "kernel": "Emotion regulation under load",
    "function": "Cost",
    "heuristic": "Impairment vs Inconvenience",
    "prompt": "Tipping over emotionally this month cost me a conversation, a relationship, or work I cared about.",
    "enterprisePrompt": "Tipping over emotionally this month cost me a conversation, a relationship, or work I cared about.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C7-Disc",
    "kernelId": "C7",
    "domain": "Cognition",
    "kernel": "Emotion regulation under load",
    "function": "Discriminator",
    "heuristic": "Trait vs State",
    "prompt": "The reaction is tied to mental demand itself; it can happen even when the situation is not emotionally important.",
    "enterprisePrompt": "The reaction is tied to mental demand itself; it can happen even when the situation is not emotionally important.",
    "privatePrompt": "The reaction is tied to mental demand itself; it can happen even when the situation is not emotionally important.",
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C7-Mod",
    "kernelId": "C7",
    "domain": "Cognition",
    "kernel": "Emotion regulation under load",
    "function": "Modifiability",
    "heuristic": "Modifiable vs Stuck",
    "prompt": "Reducing input in the moment - pausing the conversation, lowering noise, or writing the next step - helps the reaction settle.",
    "enterprisePrompt": "Reducing input in the moment - pausing the conversation, lowering noise, or writing the next step - helps the reaction settle.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C8-Sig",
    "kernelId": "C8",
    "domain": "Cognition",
    "kernel": "Recovery after cog overload",
    "function": "Signal",
    "heuristic": "Break vs not",
    "prompt": "After a mentally demanding day that used to be manageable, I now need substantially more recovery before clear thinking returns.",
    "enterprisePrompt": "After a mentally demanding day that used to be manageable, I now need substantially more recovery before clear thinking returns.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C8-Cost",
    "kernelId": "C8",
    "domain": "Cognition",
    "kernel": "Recovery after cog overload",
    "function": "Cost",
    "heuristic": "Impairment vs Inconvenience",
    "prompt": "This month, recovery after cognitive demand took long enough that the next day's work, home, or relationship responsibilities suffered.",
    "enterprisePrompt": "This month, recovery after cognitive demand took long enough that the next day's work, home, or relationship responsibilities suffered.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C8-Disc",
    "kernelId": "C8",
    "domain": "Cognition",
    "kernel": "Recovery after cog overload",
    "function": "Discriminator",
    "heuristic": "Trait vs State (chemistry/drift-led)",
    "prompt": "The recovery lag is happening after normal demands for my life, not only after unusually intense weeks.",
    "enterprisePrompt": "The recovery lag is happening after normal demands for my life, not only after unusually intense weeks.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "C8-Mod",
    "kernelId": "C8",
    "domain": "Cognition",
    "kernel": "Recovery after cog overload",
    "function": "Modifiability",
    "heuristic": "Modifiable vs Stuck",
    "prompt": "Planned recovery before and after demanding periods changes how long the depletion lasts.",
    "enterprisePrompt": "Planned recovery before and after demanding periods changes how long the depletion lasts.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "H1-Sig",
    "kernelId": "H1",
    "domain": "Chemistry",
    "kernel": "Sleep restoration",
    "function": "Signal",
    "heuristic": "Break vs not",
    "prompt": "Even with adequate hours, I wake unrested or take a long time to feel mentally online.",
    "enterprisePrompt": "Even with adequate hours, I wake unrested or take a long time to feel mentally online.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "menopause-specificity",
      "sleep-recovery"
    ]
  },
  {
    "id": "H1-Cost",
    "kernelId": "H1",
    "domain": "Chemistry",
    "kernel": "Sleep restoration",
    "function": "Cost",
    "heuristic": "Impairment vs Inconvenience",
    "prompt": "Within a day or two of fragmented or unrestorative sleep, my focus, mood, or judgment changes enough that I notice it.",
    "enterprisePrompt": "Within a day or two of fragmented or unrestorative sleep, my focus, mood, or judgment changes enough that I notice it.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "menopause-specificity",
      "sleep-recovery"
    ]
  },
  {
    "id": "H1-Disc",
    "kernelId": "H1",
    "domain": "Chemistry",
    "kernel": "Sleep restoration",
    "function": "Discriminator",
    "heuristic": "Trait vs State (chemistry-led)",
    "prompt": "Sleep disruption often has a physical driver I can name, such as temperature, night sweats, body agitation, bathroom trips, alcohol, or late caffeine.",
    "enterprisePrompt": "Sleep disruption often has a physical driver I can name, not only worry or schedule.",
    "privatePrompt": "Sleep disruption often has a physical driver I can name, such as temperature, night sweats, body agitation, bathroom trips, alcohol, or late caffeine.",
    "routing": "Both - different versions",
    "evidenceThemes": [
      "menopause-specificity",
      "sleep-recovery"
    ]
  },
  {
    "id": "H1-Mod",
    "kernelId": "H1",
    "domain": "Chemistry",
    "kernel": "Sleep restoration",
    "function": "Modifiability",
    "heuristic": "Modifiable vs Stuck",
    "prompt": "When sleep is more consolidated for two or more nights, next-day focus, mood, or word-finding noticeably improves.",
    "enterprisePrompt": "When sleep is more consolidated for two or more nights, next-day focus, mood, or word-finding noticeably improves.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "menopause-specificity",
      "sleep-recovery"
    ]
  },
  {
    "id": "H2-Sig",
    "kernelId": "H2",
    "domain": "Chemistry",
    "kernel": "Hormonal variability",
    "function": "Signal",
    "heuristic": "Break vs not",
    "prompt": "My focus, mood, or energy has recognizable swings across the month or transition stage, even if I cannot predict exact days.",
    "enterprisePrompt": "My focus, mood, or energy has recognizable swings across the month or transition stage, even if I cannot predict exact days.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "menopause-specificity",
      "menopause-cognition"
    ]
  },
  {
    "id": "H2-Cost",
    "kernelId": "H2",
    "domain": "Chemistry",
    "kernel": "Hormonal variability",
    "function": "Cost",
    "heuristic": "Impairment vs Inconvenience",
    "prompt": "This past month, a body-state swing produced a day below my usual functioning baseline.",
    "enterprisePrompt": "This past month, a body-state swing produced a day below my usual functioning baseline.",
    "privatePrompt": "This past month, a body-state swing produced a day below my usual functioning baseline.",
    "routing": "Both - different versions",
    "evidenceThemes": [
      "menopause-specificity",
      "menopause-cognition"
    ]
  },
  {
    "id": "H2-Disc",
    "kernelId": "H2",
    "domain": "Chemistry",
    "kernel": "Hormonal variability",
    "function": "Discriminator",
    "heuristic": "Trait vs State (chemistry-led)",
    "prompt": "The swings line up more with cycle changes, vasomotor symptoms, sleep disruption, or hormone-related treatment changes than with workload alone.",
    "enterprisePrompt": "The swings line up more with body-state changes or sleep disruption than with workload alone.",
    "privatePrompt": "The swings line up more with cycle changes, vasomotor symptoms, sleep disruption, or hormone-related treatment changes than with workload alone.",
    "routing": "Both - different versions",
    "evidenceThemes": [
      "menopause-specificity",
      "menopause-cognition"
    ]
  },
  {
    "id": "H2-Mod",
    "kernelId": "H2",
    "domain": "Chemistry",
    "kernel": "Hormonal variability",
    "function": "Modifiability",
    "heuristic": "Modifiable vs Stuck",
    "prompt": "Tracking sleep, symptoms, timing, and demand helps me plan better days and lower-demand days more accurately.",
    "enterprisePrompt": "Tracking sleep, symptoms, timing, and demand helps me plan better days and lower-demand days more accurately.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "menopause-specificity",
      "menopause-cognition"
    ]
  },
  {
    "id": "H3-Sig",
    "kernelId": "H3",
    "domain": "Chemistry",
    "kernel": "Energy stability",
    "function": "Signal",
    "heuristic": "Break vs not",
    "prompt": "My energy is unpredictable across the day - strong stretches followed by abrupt drops without clear cause.",
    "enterprisePrompt": "My energy is unpredictable across the day - strong stretches followed by abrupt drops without clear cause.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "menopause-specificity"
    ]
  },
  {
    "id": "H3-Cost",
    "kernelId": "H3",
    "domain": "Chemistry",
    "kernel": "Energy stability",
    "function": "Cost",
    "heuristic": "Impairment vs Inconvenience",
    "prompt": "Energy crashes this month forced me to cancel, postpone, or under-deliver on plans that mattered.",
    "enterprisePrompt": "Energy crashes this month forced me to cancel, postpone, or under-deliver on plans that mattered.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "menopause-specificity"
    ]
  },
  {
    "id": "H3-Disc",
    "kernelId": "H3",
    "domain": "Chemistry",
    "kernel": "Energy stability",
    "function": "Discriminator",
    "heuristic": "Trait vs State (chemistry-led)",
    "prompt": "Crashes happen on days with adequate sleep, food, and reasonable demand - not only on overloaded days.",
    "enterprisePrompt": "Crashes happen on days with adequate sleep, food, and reasonable demand - not only on overloaded days.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "menopause-specificity"
    ]
  },
  {
    "id": "H3-Mod",
    "kernelId": "H3",
    "domain": "Chemistry",
    "kernel": "Energy stability",
    "function": "Modifiability",
    "heuristic": "Modifiable vs Stuck",
    "prompt": "Planning demanding work inside known higher-energy windows improves outcomes more than scheduling by calendar convenience.",
    "enterprisePrompt": "Planning demanding work inside known higher-energy windows improves outcomes more than scheduling by calendar convenience.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "menopause-specificity"
    ]
  },
  {
    "id": "H4-Sig",
    "kernelId": "H4",
    "domain": "Chemistry",
    "kernel": "Stress physiology",
    "function": "Signal",
    "heuristic": "Break vs not",
    "prompt": "My body stays revved up after stress passes - restless, tense, or wired-but-tired even when the trigger is over.",
    "enterprisePrompt": "My body stays revved up after stress passes - restless, tense, or wired-but-tired even when the trigger is over.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing",
      "safety-referral"
    ]
  },
  {
    "id": "H4-Cost",
    "kernelId": "H4",
    "domain": "Chemistry",
    "kernel": "Stress physiology",
    "function": "Cost",
    "heuristic": "Impairment vs Inconvenience",
    "prompt": "Staying revved up after stress this month interfered with my sleep, focus, digestion, or ability to enjoy downtime.",
    "enterprisePrompt": "Staying revved up after stress this month interfered with my sleep, focus, digestion, or ability to enjoy downtime.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing",
      "safety-referral"
    ]
  },
  {
    "id": "H4-Disc",
    "kernelId": "H4",
    "domain": "Chemistry",
    "kernel": "Stress physiology",
    "function": "Discriminator",
    "heuristic": "Trait vs State (chemistry/threat-led)",
    "prompt": "My body revs up even at small or imagined stressors, not only during genuinely demanding events.",
    "enterprisePrompt": "My body revs up even at small or imagined stressors, not only during genuinely demanding events.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing",
      "safety-referral"
    ]
  },
  {
    "id": "H4-Mod",
    "kernelId": "H4",
    "domain": "Chemistry",
    "kernel": "Stress physiology",
    "function": "Modifiability",
    "heuristic": "Modifiable vs Stuck",
    "prompt": "A concrete downshift - walking, breathing, quiet, shower, or movement - reduces body activation within about 30 minutes.",
    "enterprisePrompt": "A concrete downshift - walking, breathing, quiet, shower, or movement - reduces body activation within about 30 minutes.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing",
      "safety-referral"
    ]
  },
  {
    "id": "H5-Sig",
    "kernelId": "H5",
    "domain": "Chemistry",
    "kernel": "Glucose/appetite/caffeine rhythm",
    "function": "Signal",
    "heuristic": "Break vs not",
    "prompt": "When I go too long without food, or when caffeine timing is off, my thinking changes within a few hours.",
    "enterprisePrompt": "When I go too long without food, or when caffeine timing is off, my thinking changes within a few hours.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "H5-Cost",
    "kernelId": "H5",
    "domain": "Chemistry",
    "kernel": "Glucose/appetite/caffeine rhythm",
    "function": "Cost",
    "heuristic": "Impairment vs Inconvenience",
    "prompt": "This month, food or caffeine timing contributed to a crash, irritability, or scattered thinking that changed what I could get done.",
    "enterprisePrompt": "This month, food or caffeine timing contributed to a crash, irritability, or scattered thinking that changed what I could get done.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "H5-Disc",
    "kernelId": "H5",
    "domain": "Chemistry",
    "kernel": "Glucose/appetite/caffeine rhythm",
    "function": "Discriminator",
    "heuristic": "Trait vs State (chemistry-led)",
    "prompt": "Focus or mood shifts happen even when the task is familiar; food, hydration, or caffeine timing is the clearer variable.",
    "enterprisePrompt": "Focus or mood shifts happen even when the task is familiar; food, hydration, or caffeine timing is the clearer variable.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "H5-Mod",
    "kernelId": "H5",
    "domain": "Chemistry",
    "kernel": "Glucose/appetite/caffeine rhythm",
    "function": "Modifiability",
    "heuristic": "Modifiable vs Stuck",
    "prompt": "A predictable meal rhythm, hydration plan, or caffeine cutoff changes the afternoon pattern enough for me to notice.",
    "enterprisePrompt": "A predictable meal rhythm, hydration plan, or caffeine cutoff changes the afternoon pattern enough for me to notice.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "H6-Sig",
    "kernelId": "H6",
    "domain": "Chemistry",
    "kernel": "Somatic burden",
    "function": "Signal",
    "heuristic": "Break vs not",
    "prompt": "Body discomfort pulls attention away from thinking, such as pain, headaches, gut symptoms, temperature shifts, or tension.",
    "enterprisePrompt": "Body discomfort pulls attention away from thinking, such as pain, headaches, gut symptoms, temperature shifts, or tension.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "menopause-specificity"
    ]
  },
  {
    "id": "H6-Cost",
    "kernelId": "H6",
    "domain": "Chemistry",
    "kernel": "Somatic burden",
    "function": "Cost",
    "heuristic": "Impairment vs Inconvenience",
    "prompt": "This month, body symptoms changed what I could attend, finish, tolerate, or recover from.",
    "enterprisePrompt": "This month, body symptoms changed what I could attend, finish, tolerate, or recover from.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "menopause-specificity"
    ]
  },
  {
    "id": "H6-Disc",
    "kernelId": "H6",
    "domain": "Chemistry",
    "kernel": "Somatic burden",
    "function": "Discriminator",
    "heuristic": "Trait vs State (chemistry-led)",
    "prompt": "Body symptoms worsen in recognizable conditions such as poor sleep, heat, stress load, cycle or transition changes, or prolonged sitting.",
    "enterprisePrompt": "Body symptoms worsen in recognizable conditions such as poor sleep, heat, stress load, or prolonged sitting.",
    "privatePrompt": "Body symptoms worsen in recognizable conditions such as poor sleep, heat, stress load, cycle or transition changes, or prolonged sitting.",
    "routing": "Both - different versions",
    "evidenceThemes": [
      "menopause-specificity"
    ]
  },
  {
    "id": "H6-Mod",
    "kernelId": "H6",
    "domain": "Chemistry",
    "kernel": "Somatic burden",
    "function": "Modifiability",
    "heuristic": "Modifiable vs Stuck",
    "prompt": "A specific body support I can name reduces the distraction enough to improve functioning.",
    "enterprisePrompt": "A specific body support I can name reduces the distraction enough to improve functioning.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "menopause-specificity"
    ]
  },
  {
    "id": "H7-Sig",
    "kernelId": "H7",
    "domain": "Chemistry",
    "kernel": "Medication/substance/supplement",
    "function": "Signal",
    "heuristic": "Break vs not",
    "prompt": "Something I take or use clearly changes my focus, mood, sleep, or energy.",
    "enterprisePrompt": "Something I take or use clearly changes my focus, mood, sleep, or energy.",
    "privatePrompt": "Something I take or use clearly changes my focus, mood, sleep, or energy.",
    "routing": "Both - different versions",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "H7-Cost",
    "kernelId": "H7",
    "domain": "Chemistry",
    "kernel": "Medication/substance/supplement",
    "function": "Cost",
    "heuristic": "Impairment vs Inconvenience",
    "prompt": "This month, side effects, wearing-off, rebound, or timing effects from something I take or use disrupted my day.",
    "enterprisePrompt": null,
    "privatePrompt": "This month, side effects, wearing-off, rebound, or timing effects from something I take or use disrupted my day.",
    "routing": "Private only",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "H7-Disc",
    "kernelId": "H7",
    "domain": "Chemistry",
    "kernel": "Medication/substance/supplement",
    "function": "Discriminator",
    "heuristic": "Trait vs State (chemistry-led)",
    "prompt": "The pattern seems linked to timing, missed doses, dose changes, or wearing-off periods more than to workload alone.",
    "enterprisePrompt": null,
    "privatePrompt": "The pattern seems linked to timing, missed doses, dose changes, or wearing-off periods more than to workload alone.",
    "routing": "Private only",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "H7-Mod",
    "kernelId": "H7",
    "domain": "Chemistry",
    "kernel": "Medication/substance/supplement",
    "function": "Modifiability",
    "heuristic": "Modifiable vs Stuck",
    "prompt": "When timing is consistent, I can tell more clearly whether the pattern improves, worsens, or stays the same.",
    "enterprisePrompt": null,
    "privatePrompt": "When timing is consistent, I can tell more clearly whether the pattern improves, worsens, or stays the same.",
    "routing": "Private only",
    "evidenceThemes": [
      "dimensional-framing"
    ]
  },
  {
    "id": "H8-Sig",
    "kernelId": "H8",
    "domain": "Chemistry",
    "kernel": "Recovery physiology",
    "function": "Signal",
    "heuristic": "Break vs not",
    "prompt": "After ordinary effort or a busy week, my body takes longer to recover than it used to.",
    "enterprisePrompt": "After ordinary effort or a busy week, my body takes longer to recover than it used to.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "menopause-specificity",
      "sleep-recovery"
    ]
  },
  {
    "id": "H8-Cost",
    "kernelId": "H8",
    "domain": "Chemistry",
    "kernel": "Recovery physiology",
    "function": "Cost",
    "heuristic": "Impairment vs Inconvenience",
    "prompt": "Slow physical recovery this month meant cancelled plans, lost weekends, or under-functioning at work.",
    "enterprisePrompt": "Slow physical recovery this month meant cancelled plans, lost weekends, or under-functioning at work.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "menopause-specificity",
      "sleep-recovery"
    ]
  },
  {
    "id": "H8-Disc",
    "kernelId": "H8",
    "domain": "Chemistry",
    "kernel": "Recovery physiology",
    "function": "Discriminator",
    "heuristic": "Trait vs State (chemistry/drift-led)",
    "prompt": "Recovery has slowed compared with my prior baseline at the same workload - not only after exceptional weeks.",
    "enterprisePrompt": "Recovery has slowed compared with my prior baseline at the same workload - not only after exceptional weeks.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "menopause-specificity",
      "sleep-recovery"
    ]
  },
  {
    "id": "H8-Mod",
    "kernelId": "H8",
    "domain": "Chemistry",
    "kernel": "Recovery physiology",
    "function": "Modifiability",
    "heuristic": "Modifiable vs Stuck",
    "prompt": "Planned recovery before and after demanding periods changes the length of the crash.",
    "enterprisePrompt": "Planned recovery before and after demanding periods changes the length of the crash.",
    "privatePrompt": null,
    "routing": "Both",
    "evidenceThemes": [
      "menopause-specificity",
      "sleep-recovery"
    ]
  }
];

export const RESPONSE_SCALE: ResponseScaleOption[] = [
  { value: 0, label: 'Never or almost never' },
  { value: 1, label: 'Rarely' },
  { value: 2, label: 'Sometimes' },
  { value: 3, label: 'Often' },
  { value: 4, label: 'Very often or almost always' }
];

export const CONTEXT_PROMPTS: ContextPrompt[] = [
  { id: 'role_type', label: 'Current work or role pattern', type: 'choice', options: ['Heavy-output knowledge work', 'Leadership or management', 'Clinical/caregiving/front-line', 'Mixed creative and operational', 'Self-employed or portfolio', 'Out of paid work currently', 'Other'] },
  { id: 'meeting_load', label: 'Weekly meeting and interruption load', type: 'choice', options: ['Under 5 hours', '5 to 15 hours', '15 to 25 hours', '25+ hours'] },
  { id: 'sleep_stability', label: 'Sleep and wake timing across a typical week', type: 'choice', options: ['Very consistent', 'Mostly consistent', 'Variable', 'Highly disrupted'] },
  { id: 'transition_context', label: 'Hormonal-transition context', type: 'choice', options: ['Cycling regularly', 'Cycling irregularly', 'Perimenopausal', 'Postmenopausal', 'On hormonal contraception', 'On menopausal hormone therapy', 'Prefer not to say'] },
  { id: 'lifelong_attention_pattern', label: 'Attention and organization before midlife', type: 'choice', options: ['Longstanding since childhood or teen years', 'Present for many adult years', 'Mainly changed in midlife', 'Mainly appears under high stress', 'Unsure'] },
  { id: 'setting_spread', label: 'Where the pattern shows up', type: 'choice', options: ['Across work, home, and relationships', 'Mostly at work', 'Mostly at home', 'Mostly during hormonal or sleep disruption', 'Only in unusual stress', 'Unsure'] },
  { id: 'timeline', label: 'Compared with five years ago, current functional capacity is...', type: 'choice', options: ['Clearly better', 'About the same', 'Somewhat worse', 'Significantly worse', 'Has fluctuated'] }
];

export const NARRATIVE_PROMPTS: NarrativePrompt[] = [
  { id: 'compensating_for', label: 'What are you most tired of compensating for?' },
  { id: 'public_private_cost', label: 'Where do you function well publicly but pay for it privately?' },
  { id: 'capacity_shift', label: 'If next month felt 25% easier to function in, what would change first?' },
  { id: 'what_helped', label: 'What have you already tried that helped, even briefly?' }
];

export const SAFETY_ITEMS: SafetyItem[] = [
  { id: 'S1', prompt: 'My sleep has been severely reduced lately, but my energy or mood has noticeably increased.', flag: 'Possible mania or hypomania pattern' },
  { id: 'S2', prompt: 'My cognition has changed suddenly, severely, or in a way that feels medically unusual.', flag: 'Sudden or medically unusual cognitive change' },
  { id: 'S3', prompt: 'Something I take or use is starting to feel hard to control, risky, or concerning to me or someone close to me.', flag: 'Substance, medication, or supplement concern' },
  { id: 'S4', prompt: 'My functioning has declined to the point that my safety, basic self-care, or stability is at risk.', flag: 'Safety, self-care, or stability concern' }
];
